name: Build golang-gcc-modd and Publish Docker

on:
  push:
    paths:
      - 1.17-modd/*
    branches:
      - master
    tags:
      - v1.*
      - v2.*
      - v3.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: bigrocs/golang-gcc-modd
          dockerfile: ./1.17-modd/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: v1.17
